name: Build and Release

on:
  push:
    tags:
      - 'v*' # Сработает, когда вы отправите тег вроде v0.0.3

permissions:
  contents: write # Дает право GitHub Actions создавать релиз и загружать файлы

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: build/Release/UltraIDE.exe
